import type {
  IntelligenceModeDefinition,
  IntelligenceModeFamily,
  IntelligenceModeId,
  LearnWeightingProfile,
  ModeAvailability,
  RecommendedSourceKind,
} from "@/types/modes";

export const ACTIVE_INTELLIGENCE_MODE_IDS = [
  "executive-brief",
  "the-student",
  "the-creator",
  "contract-analyzer",
] as const satisfies readonly IntelligenceModeId[];

export type ActiveIntelligenceModeId = (typeof ACTIVE_INTELLIGENCE_MODE_IDS)[number];

const SRC = {
  any: ["any"] as RecommendedSourceKind[],
  doc: ["pdf", "docx", "txt", "web"] as RecommendedSourceKind[],
  media: ["youtube", "pptx", "web", "pdf"] as RecommendedSourceKind[],
  document: ["pdf", "docx", "web"] as RecommendedSourceKind[],
};

function m(
  def: IntelligenceModeDefinition,
): IntelligenceModeDefinition {
  return def;
}

const W = {
  balanced: {
    concept: 1,
    why_it_matters: 1,
    memory_hook: 1,
    quiz: 1,
    connection: 1,
    misconception: 1,
  } satisfies LearnWeightingProfile,
  quizHeavy: {
    concept: 1.2,
    quiz: 1.6,
    memory_hook: 0.9,
    connection: 0.4,
    misconception: 0.7,
    why_it_matters: 0.7,
  },
  connectionHeavy: {
    connection: 1.6,
    concept: 1,
    why_it_matters: 1,
    memory_hook: 1.1,
    quiz: 0.6,
    misconception: 0.8,
  },
  decisionHeavy: {
    why_it_matters: 1.5,
    concept: 1.1,
    misconception: 1,
    quiz: 0.7,
    connection: 0.8,
    memory_hook: 0.7,
  },
  criticalHeavy: {
    misconception: 1.6,
    connection: 1.2,
    concept: 1.1,
    why_it_matters: 1,
    quiz: 0.8,
    memory_hook: 0.6,
  },
  creatorHeavy: {
    memory_hook: 1.4,
    connection: 1.3,
    concept: 1,
    why_it_matters: 1,
    quiz: 0.7,
    misconception: 0.6,
  },
};

function locked(
  partial: Omit<IntelligenceModeDefinition, "availability"> & {
    availability?: ModeAvailability;
  },
): IntelligenceModeDefinition {
  return m({
    availability: partial.comingSoon ? "coming_soon" : "locked",
    ...partial,
  });
}

export const INTELLIGENCE_MODES: IntelligenceModeDefinition[] = [
  m({
    id: "general-summary",
    label: "General Summary",
    shortDescription: "Balanced overview for any document type.",
    intelligenceLens: "Clear overview of what the source says and why it matters.",
    outputStylePreview: "Neutral summary · key themes · light risks",
    learnEmphasis: "Balanced concept and insight cards",
    category: "core",
    icon: "layers",
    availability: "locked",
    intelligenceFamily: "executive",
    learnWeighting: W.balanced,
    outputTone: "analytical",
    outputDepth: "standard",
    recommendedSources: SRC.any,
  }),
  m({
    id: "key-points",
    label: "Key Points",
    shortDescription: "Bullet-first extraction of the strongest claims.",
    intelligenceLens: "Surfaces the highest-signal points without narrative fluff.",
    outputStylePreview: "Tight bullets · scannable · minimal prose",
    learnEmphasis: "Concept cards weighted toward takeaways",
    category: "core",
    icon: "list",
    availability: "locked",
    intelligenceFamily: "executive",
    learnWeighting: { concept: 1.3, why_it_matters: 1.1, quiz: 0.8 },
    outputTone: "analytical",
    outputDepth: "brief",
    recommendedSources: SRC.any,
  }),
  m({
    id: "executive-brief",
    label: "Executive Brief",
    shortDescription: "C-suite clarity: decisions, tradeoffs, and implications.",
    intelligenceLens: "Strategic synthesis for leadership readers — decisions, risks, and next steps.",
    outputStylePreview: "Decision-focused · implications · concise risks",
    learnEmphasis: "Why-it-matters and concept cards for leadership",
    category: "core",
    icon: "briefcase",
    availability: "active",
    intelligenceFamily: "executive",
    learnWeighting: W.decisionHeavy,
    outputTone: "strategic",
    outputDepth: "brief",
    recommendedSources: SRC.doc,
    promptAdjunct:
      "Prioritize decisions, tradeoffs, business implications, and explicit next steps.",
  }),
  locked({
    id: "deep-dive",
    label: "Deep Dive",
    shortDescription: "Long-form synthesis with structure and tension.",
    intelligenceLens: "Extended analysis across sections, arguments, and gaps.",
    outputStylePreview: "Multi-section · nuanced · evidence-aware",
    learnEmphasis: "More concept and connection depth",
    category: "core",
    icon: "telescope",
    intelligenceFamily: "academic",
    learnWeighting: { concept: 1.3, connection: 1.2, misconception: 1.1 },
    outputTone: "analytical",
    outputDepth: "detailed",
    recommendedSources: SRC.doc,
  }),

  m({
    id: "the-student",
    label: "The Student",
    shortDescription: "Study-friendly concepts, definitions, and recall hooks.",
    intelligenceLens: "Turns sources into teachable notes: concepts, definitions, and study questions.",
    outputStylePreview: "Study notes · definitions · recall-friendly",
    learnEmphasis: "Concept, quiz, and misconception cards",
    category: "academic_study",
    icon: "graduation-cap",
    availability: "active",
    intelligenceFamily: "academic",
    learnWeighting: W.quizHeavy,
    outputTone: "analytical",
    outputDepth: "standard",
    recommendedSources: SRC.doc,
    promptAdjunct: "Emphasize teachable concepts, definitions, and active-recall-friendly insights.",
  }),
  locked({
    id: "the-researcher",
    label: "The Researcher",
    shortDescription: "Arguments, evidence, contradictions, and methodology.",
    intelligenceLens: "Extracts arguments, concepts, contradictions, and evidence structures.",
    outputStylePreview: "Thesis · evidence · limitations",
    learnEmphasis: "Concept and misconception depth",
    category: "academic_study",
    icon: "microscope",
    intelligenceFamily: "academic",
    learnWeighting: W.criticalHeavy,
    outputTone: "analytical",
    outputDepth: "detailed",
    recommendedSources: SRC.doc,
  }),
  locked({
    id: "exam-prep",
    label: "Exam Prep",
    shortDescription: "High-yield facts and likely test angles.",
    intelligenceLens: "Prioritizes exam-relevant facts, contrasts, and likely question angles.",
    outputStylePreview: "High-yield · contrasts · drill-ready",
    learnEmphasis: "Quiz and concept cards prioritized",
    category: "academic_study",
    icon: "clipboard-check",
    intelligenceFamily: "academic",
    learnWeighting: W.quizHeavy,
    outputTone: "analytical",
    outputDepth: "standard",
    recommendedSources: SRC.doc,
  }),
  locked({
    id: "flashcard-builder",
    label: "Flashcard Builder",
    shortDescription: "Short front/back style learn assets.",
    intelligenceLens: "Compresses ideas into flashcard-friendly prompts and answers.",
    outputStylePreview: "Short prompts · crisp answers",
    learnEmphasis: "Heavy quiz and concept cards",
    category: "academic_study",
    icon: "cards",
    intelligenceFamily: "academic",
    learnWeighting: { quiz: 1.8, concept: 1.4, memory_hook: 1.1 },
    outputTone: "analytical",
    outputDepth: "brief",
    recommendedSources: SRC.doc,
  }),
  locked({
    id: "quiz-generator",
    label: "Quiz Generator",
    shortDescription: "Active-recall questions from source claims.",
    intelligenceLens: "Builds quiz-worthy questions tied to explicit source claims.",
    outputStylePreview: "Questions · answers · difficulty spread",
    learnEmphasis: "Quiz-first learn layer",
    category: "academic_study",
    icon: "help-circle",
    intelligenceFamily: "academic",
    learnWeighting: { quiz: 2, concept: 1.2 },
    outputTone: "analytical",
    outputDepth: "standard",
    recommendedSources: SRC.doc,
  }),
  locked({
    id: "concept-explainer",
    label: "Concept Explainer",
    shortDescription: "Defines and links core ideas clearly.",
    intelligenceLens: "Explains terms and ideas as if teaching a motivated reader.",
    outputStylePreview: "Definitions · examples · links between ideas",
    learnEmphasis: "Concept and connection cards",
    category: "academic_study",
    icon: "lightbulb",
    intelligenceFamily: "academic",
    learnWeighting: { concept: 1.5, connection: 1.2 },
    outputTone: "analytical",
    outputDepth: "standard",
    recommendedSources: SRC.any,
  }),

  locked({
    id: "the-executive",
    label: "The Executive",
    shortDescription: "Board-ready narrative with strategic stakes.",
    intelligenceLens: "Executive narrative: stakes, options, and recommended direction.",
    outputStylePreview: "Stake framing · options · recommendation",
    learnEmphasis: "Why-it-matters emphasis",
    category: "business_strategy",
    icon: "trending-up",
    intelligenceFamily: "executive",
    learnWeighting: W.decisionHeavy,
    outputTone: "strategic",
    outputDepth: "standard",
    recommendedSources: SRC.doc,
  }),
  locked({
    id: "swot-analyzer",
    label: "SWOT Analyzer",
    shortDescription: "Strengths, weaknesses, opportunities, threats.",
    intelligenceLens: "Maps source content into SWOT-style strategic buckets when supported.",
    outputStylePreview: "SWOT buckets · evidence-tagged",
    learnEmphasis: "Concept and why cards per quadrant theme",
    category: "business_strategy",
    icon: "grid",
    intelligenceFamily: "executive",
    learnWeighting: { concept: 1.3, why_it_matters: 1.2, connection: 1 },
    outputTone: "strategic",
    outputDepth: "standard",
    recommendedSources: SRC.doc,
  }),
  locked({
    id: "market-analyst",
    label: "Market Analyst",
    shortDescription: "Market dynamics, competitors, and positioning.",
    intelligenceLens: "Highlights market structure, competitors, and positioning signals.",
    outputStylePreview: "Market map · competitors · signals",
    learnEmphasis: "Concept and connection between market forces",
    category: "business_strategy",
    icon: "bar-chart",
    intelligenceFamily: "executive",
    learnWeighting: { concept: 1.2, connection: 1.3, why_it_matters: 1.1 },
    outputTone: "strategic",
    outputDepth: "standard",
    recommendedSources: SRC.doc,
  }),
  locked({
    id: "startup-advisor",
    label: "Startup Advisor",
    shortDescription: "Problem, solution, traction, and GTM hints.",
    intelligenceLens: "Startup lens: problem, solution, market, traction, and GTM signals.",
    outputStylePreview: "Problem/solution · traction · risks",
    learnEmphasis: "Why and concept for founder decisions",
    category: "business_strategy",
    icon: "rocket",
    intelligenceFamily: "executive",
    learnWeighting: W.decisionHeavy,
    outputTone: "strategic",
    outputDepth: "standard",
    recommendedSources: ["pptx", "pdf", "web"],
  }),
  locked({
    id: "meeting-notes-ai",
    label: "Meeting Notes AI",
    shortDescription: "Decisions, owners, and follow-ups from notes.",
    intelligenceLens: "Extracts decisions, action items, owners, and open questions.",
    outputStylePreview: "Decisions · actions · open questions",
    learnEmphasis: "Why-it-matters and action-oriented framing",
    category: "business_strategy",
    icon: "users",
    intelligenceFamily: "executive",
    learnWeighting: { why_it_matters: 1.4, concept: 1 },
    outputTone: "strategic",
    outputDepth: "brief",
    recommendedSources: ["txt", "docx", "pdf"],
  }),

  locked({
    id: "the-journalist",
    label: "The Journalist",
    shortDescription: "Who, what, when, why — with sourced claims.",
    intelligenceLens: "Journalistic clarity: claims, sources, stakes, and narrative arc.",
    outputStylePreview: "Lead · claims · context · what's new",
    learnEmphasis: "Concept and why with crisp framing",
    category: "content_media",
    icon: "newspaper",
    intelligenceFamily: "creator",
    learnWeighting: { concept: 1.2, why_it_matters: 1.2 },
    outputTone: "narrative",
    outputDepth: "standard",
    recommendedSources: SRC.media,
  }),
  m({
    id: "the-creator",
    label: "The Creator",
    shortDescription: "Hooks, angles, repurposable moments, and audience tension.",
    intelligenceLens:
      "Finds hooks, emotional angles, repurposable moments, and social-first insights.",
    outputStylePreview: "Hooks · beats · repurposing angles",
    learnEmphasis: "Hook, connection, and memory cards",
    category: "content_media",
    icon: "sparkles",
    availability: "active",
    intelligenceFamily: "creator",
    learnWeighting: W.creatorHeavy,
    outputTone: "creative",
    outputDepth: "standard",
    recommendedSources: SRC.media,
    promptAdjunct:
      "Prioritize hooks, narrative beats, clip-worthy moments, and repurposable content angles.",
  }),
  locked({
    id: "script-breakdown",
    label: "Script Breakdown",
    shortDescription: "Scenes, beats, and dialogue intelligence.",
    intelligenceLens: "Breaks scripts into beats, scenes, and dramatic turns.",
    outputStylePreview: "Beat sheet · scenes · character drivers",
    learnEmphasis: "Connection and memory hook cards",
    category: "content_media",
    icon: "clapperboard",
    intelligenceFamily: "creator",
    learnWeighting: W.connectionHeavy,
    outputTone: "narrative",
    outputDepth: "detailed",
    recommendedSources: ["pdf", "docx", "txt"],
  }),
  locked({
    id: "podcast-summary",
    label: "Podcast Summary",
    shortDescription: "Episode arc, guests, and quotable moments.",
    intelligenceLens: "Episode structure, themes, guests, and quotable beats.",
    outputStylePreview: "Episode arc · themes · quotes",
    learnEmphasis: "Creator-style hooks and concepts",
    category: "content_media",
    icon: "mic",
    intelligenceFamily: "creator",
    learnWeighting: W.creatorHeavy,
    outputTone: "narrative",
    outputDepth: "standard",
    recommendedSources: ["youtube", "txt", "web"],
  }),
  locked({
    id: "youtube-intelligence",
    label: "YouTube Intelligence",
    shortDescription: "Transcript-native video analysis.",
    intelligenceLens: "Optimized for spoken transcripts: argument flow and clip moments.",
    outputStylePreview: "Thesis · moments · viewer takeaways",
    learnEmphasis: "Hooks and timestamp-friendly insights",
    category: "content_media",
    icon: "play-circle",
    intelligenceFamily: "creator",
    learnWeighting: W.creatorHeavy,
    outputTone: "creative",
    outputDepth: "standard",
    recommendedSources: ["youtube"],
    comingSoon: true,
  }),

  locked({
    id: "action-items",
    label: "Action Items",
    shortDescription: "Concrete next steps with owners when present.",
    intelligenceLens: "Pulls actionable tasks, owners, and deadlines when stated.",
    outputStylePreview: "Action list · owners · priorities",
    learnEmphasis: "Why-it-matters tied to each action",
    category: "productivity",
    icon: "check-square",
    intelligenceFamily: "executive",
    learnWeighting: W.decisionHeavy,
    outputTone: "strategic",
    outputDepth: "brief",
    recommendedSources: SRC.doc,
  }),
  locked({
    id: "smart-notes",
    label: "Smart Notes",
    shortDescription: "Structured notes with headings and links.",
    intelligenceLens: "Organized notes with headings, links, and callouts.",
    outputStylePreview: "Structured notes · callouts",
    learnEmphasis: "Concept and connection cards",
    category: "productivity",
    icon: "notebook",
    intelligenceFamily: "academic",
    learnWeighting: { concept: 1.3, connection: 1.1 },
    outputTone: "analytical",
    outputDepth: "standard",
    recommendedSources: SRC.any,
  }),
  locked({
    id: "decision-mapper",
    label: "Decision Mapper",
    shortDescription: "Options, criteria, and tradeoffs.",
    intelligenceLens: "Surfaces decisions, options, criteria, and tradeoffs.",
    outputStylePreview: "Options · criteria · recommendation",
    learnEmphasis: "Why-it-matters and connection cards",
    category: "productivity",
    icon: "git-branch",
    intelligenceFamily: "executive",
    learnWeighting: W.decisionHeavy,
    outputTone: "strategic",
    outputDepth: "standard",
    recommendedSources: SRC.doc,
  }),
  locked({
    id: "timeline-builder",
    label: "Timeline Builder",
    shortDescription: "Chronology and milestone sequencing.",
    intelligenceLens: "Builds chronological sequence and milestone map.",
    outputStylePreview: "Timeline · milestones · dependencies",
    learnEmphasis: "Connection cards across events",
    category: "productivity",
    icon: "calendar",
    intelligenceFamily: "executive",
    learnWeighting: { connection: 1.4, concept: 1, why_it_matters: 1 },
    outputTone: "analytical",
    outputDepth: "standard",
    recommendedSources: SRC.doc,
  }),

  m({
    id: "contract-analyzer",
    label: "Contract Summary",
    shortDescription: "Clauses, obligations, and points to review.",
    intelligenceLens: "Creates an informational overview of clauses, obligations, and points to review.",
    outputStylePreview: "Clauses · obligations · points to review",
    learnEmphasis: "Concept and misconception-oriented cards",
    category: "legal_technical",
    icon: "scale",
    availability: "active",
    intelligenceFamily: "legal",
    learnWeighting: { concept: 1.3, misconception: 1.2, why_it_matters: 1.1 },
    outputTone: "precise",
    outputDepth: "detailed",
    recommendedSources: SRC.document,
    promptAdjunct:
      "Summarize clauses, obligations, dates, and points to review only from the text. Do not provide recommendations or regulated professional advice.",
  }),
  locked({
    id: "technical-decoder",
    label: "Technical Decoder",
    shortDescription: "Plain-English explanation of technical material.",
    intelligenceLens: "Translates technical jargon into precise plain English.",
    outputStylePreview: "Plain English · terms defined · dependencies",
    learnEmphasis: "Concept cards with precise definitions",
    category: "legal_technical",
    icon: "cpu",
    intelligenceFamily: "legal",
    learnWeighting: { concept: 1.5, misconception: 1.1 },
    outputTone: "precise",
    outputDepth: "detailed",
    recommendedSources: SRC.doc,
  }),
  locked({
    id: "policy-interpreter",
    label: "Policy Summary",
    shortDescription: "Rules, scope, and policy notes.",
    intelligenceLens: "Summarizes policy rules, scope, and stated points to review.",
    outputStylePreview: "Rules · scope · policy notes",
    learnEmphasis: "Concept and review-oriented cards",
    category: "legal_technical",
    icon: "shield",
    intelligenceFamily: "legal",
    learnWeighting: { concept: 1.3, misconception: 1.2 },
    outputTone: "precise",
    outputDepth: "standard",
    recommendedSources: SRC.document,
  }),

  locked({
    id: "narrative-explorer",
    label: "Narrative Explorer",
    shortDescription: "Themes, arcs, and symbolic connections.",
    intelligenceLens: "Explores narrative themes, arcs, and connections across the material.",
    outputStylePreview: "Themes · arcs · motifs",
    learnEmphasis: "Connection-heavy learn cards",
    category: "creative_advanced",
    icon: "book-open",
    intelligenceFamily: "creator",
    learnWeighting: W.connectionHeavy,
    outputTone: "narrative",
    outputDepth: "detailed",
    recommendedSources: SRC.any,
  }),
  locked({
    id: "critical-thinking-mode",
    label: "Critical Thinking Mode",
    shortDescription: "Assumptions, tensions, and weak claims.",
    intelligenceLens: "Surfaces assumptions, contradictions, and weak or missing evidence.",
    outputStylePreview: "Assumptions · tensions · counterarguments",
    learnEmphasis: "Misconception and tension cards",
    category: "creative_advanced",
    icon: "brain",
    intelligenceFamily: "academic",
    learnWeighting: W.criticalHeavy,
    outputTone: "analytical",
    outputDepth: "detailed",
    recommendedSources: SRC.any,
  }),
];

const MODE_MAP = new Map(INTELLIGENCE_MODES.map((mode) => [mode.id, mode]));

export function getIntelligenceModeById(
  id: IntelligenceModeId,
): IntelligenceModeDefinition | undefined {
  return MODE_MAP.get(id);
}

export function getActiveIntelligenceModes(): IntelligenceModeDefinition[] {
  return INTELLIGENCE_MODES.filter((m) => m.availability === "active");
}

export function isActiveIntelligenceModeId(id: string): id is ActiveIntelligenceModeId {
  return (ACTIVE_INTELLIGENCE_MODE_IDS as readonly string[]).includes(id);
}

/** Legacy API mode strings → default intelligence mode id. */
export const LEGACY_MODE_TO_INTELLIGENCE_ID: Record<
  IntelligenceModeFamily,
  ActiveIntelligenceModeId
> = {
  executive: "executive-brief",
  academic: "the-student",
  creator: "the-creator",
  legal: "contract-analyzer",
};

export function resolveIntelligenceFamily(
  family: IntelligenceModeFamily,
): IntelligenceModeFamily {
  return family;
}
